#pragma once

// ============================================================================
// AllMappers.h - agregator wszystkich naglowkow mapperow.
// ----------------------------------------------------------------------------
// Wlaczany przez Cartridge.h. Dziala jako pojedyncza jednostka kompilacji
// odpowiedzialna za wyemitowanie statycznych obiektow AutoRegister, ktore
// rejestruja mappery w MapperRegistry zanim ruszy main().
//
// Dodajac nowy mapper:
//   1. utworz mappers/MapperNNN.h (wzorem istniejacych)
//   2. zakoncz plik makrem REGISTER_MAPPER(NNN, MapperNNN)
//   3. dodaj #include "mappers/MapperNNN.h" ponizej
// To wszystko - Cartridge.h nie wymaga zmian.
// ============================================================================

#include "MapperRegistry.h"

#include "Mapper000.h"
#include "Mapper001.h"
#include "Mapper002.h"
#include "Mapper003.h"
#include "Mapper004.h"
#include "Mapper007.h"
#include "Mapper009.h"
#include "Mapper010.h"
#include "Mapper011.h"
#include "Mapper013.h"
#include "Mapper015.h"
#include "Mapper024.h"
#include "Mapper026.h"
#include "Mapper032.h"
#include "Mapper033.h"
#include "Mapper034.h"
#include "Mapper044.h"
#include "Mapper046.h"
#include "Mapper047.h"
#include "Mapper048.h"
#include "Mapper049.h"
#include "Mapper057.h"
#include "Mapper058.h"
#include "Mapper060.h"
#include "Mapper061.h"
#include "Mapper062.h"
#include "Mapper064.h"
#include "Mapper067.h"
#include "Mapper065.h"
#include "Mapper066.h"
#include "Mapper068.h"
#include "Mapper070.h"
#include "Mapper071.h"
#include "Mapper072.h"
#include "Mapper073.h"
#include "Mapper074.h"
#include "Mapper075.h"
#include "Mapper076.h"
#include "Mapper077.h"
#include "Mapper078.h"
#include "Mapper079.h"
#include "Mapper080.h"
#include "Mapper082.h"
#include "Mapper087.h"
#include "Mapper088.h"
#include "Mapper089.h"
#include "Mapper091.h"
#include "Mapper092.h"
#include "Mapper093.h"
#include "Mapper094.h"
#include "Mapper095.h"
#include "Mapper097.h"
#include "Mapper107.h"
#include "Mapper112.h"
#include "Mapper113.h"
#include "Mapper115.h"
#include "Mapper118.h"
#include "Mapper119.h"
#include "Mapper140.h"
#include "Mapper152.h"
#include "Mapper154.h"
#include "Mapper164.h"
#include "Mapper180.h"
#include "Mapper182.h"
#include "Mapper184.h"
#include "Mapper185.h"
#include "Mapper189.h"
#include "Mapper191.h"
#include "Mapper192.h"
#include "Mapper193.h"
#include "Mapper194.h"
#include "Mapper200.h"
#include "Mapper201.h"
#include "Mapper203.h"
#include "Mapper205.h"
#include "Mapper225.h"
#include "Mapper226.h"
#include "Mapper227.h"
#include "Mapper228.h"
#include "Mapper230.h"
#include "Mapper231.h"
#include "Mapper232.h"
#include "Mapper233.h"
#include "Mapper234.h"
#include "Mapper240.h"
#include "Mapper242.h"
#include "Mapper243.h"
#include "Mapper245.h"
#include "Mapper246.h"
